modLoader="javafml"
loaderVersion="[31,)"

[[mods]]
modId="taskmod"
version="0.1.0"
displayName="task58Mod"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://mcreator.net"
authors="task, MCreator"
description='''
This mod is my first mod
'''

[[dependencies.taskmod]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="BOTH"




